//----------------------------------
// Interfaces
//----------------------------------
export interface CursorIndex {
  x: number;
  y: number;
}

export interface AttributeListItem {
  index: number;
  symbol?: string;
  label: string;
  description?: string;
}

//----------------------------------
// Enumerators / Constants
//----------------------------------
export enum StepProperty {
  NOTE = 'note',
  INSTRUMENT = 'instrument',
  FX1 = 'fx1',
  FX2 = 'fx2',
}

export const InstrumentList: AttributeListItem[] = [
  { index: 64, label: 'Synth 1' },
  { index: 65, label: 'Synth 2' },
  { index: 66, label: 'Synth 3' },
  { index: 0, label: 'Instrument 1' },
  { index: 1, label: 'Instrument 2' },
  { index: 2, label: 'Instrument 3' },
  { index: 3, label: 'Instrument 4' },
  { index: 4, label: 'Instrument 5' },
  { index: 5, label: 'Instrument 6' },
  { index: 6, label: 'Instrument 7' },
  { index: 7, label: 'Instrument 8' },
  { index: 8, label: 'Instrument 9' },
  { index: 9, label: 'Instrument 10' },
  { index: 10, label: 'Instrument 11' },
  { index: 11, label: 'Instrument 12' },
  { index: 12, label: 'Instrument 13' },
  { index: 13, label: 'Instrument 14' },
  { index: 14, label: 'Instrument 15' },
  { index: 15, label: 'Instrument 16' },
  { index: 16, label: 'Instrument 17' },
  { index: 17, label: 'Instrument 18' },
  { index: 18, label: 'Instrument 19' },
  { index: 19, label: 'Instrument 20' },
  { index: 20, label: 'Instrument 21' },
  { index: 21, label: 'Instrument 22' },
  { index: 22, label: 'Instrument 23' },
  { index: 23, label: 'Instrument 24' },
  { index: 24, label: 'Instrument 25' },
  { index: 25, label: 'Instrument 26' },
  { index: 26, label: 'Instrument 27' },
  { index: 27, label: 'Instrument 28' },
  { index: 28, label: 'Instrument 29' },
  { index: 29, label: 'Instrument 30' },
  { index: 30, label: 'Instrument 31' },
  { index: 31, label: 'Instrument 32' },
  { index: 32, label: 'Instrument 33' },
  { index: 33, label: 'Instrument 34' },
  { index: 34, label: 'Instrument 35' },
  { index: 35, label: 'Instrument 36' },
  { index: 36, label: 'Instrument 37' },
  { index: 37, label: 'Instrument 38' },
  { index: 38, label: 'Instrument 39' },
  { index: 39, label: 'Instrument 40' },
  { index: 40, label: 'Instrument 41' },
  { index: 41, label: 'Instrument 42' },
  { index: 42, label: 'Instrument 43' },
  { index: 43, label: 'Instrument 44' },
  { index: 44, label: 'Instrument 45' },
  { index: 45, label: 'Instrument 46' },
  { index: 46, label: 'Instrument 47' },
  { index: 47, label: 'Instrument 48' },
  { index: 48, label: 'MIDI Channel 1' },
  { index: 49, label: 'MIDI Channel 2' },
  { index: 50, label: 'MIDI Channel 3' },
  { index: 51, label: 'MIDI Channel 4' },
  { index: 52, label: 'MIDI Channel 5' },
  { index: 53, label: 'MIDI Channel 6' },
  { index: 54, label: 'MIDI Channel 7' },
  { index: 55, label: 'MIDI Channel 8' },
  { index: 56, label: 'MIDI Channel 9' },
  { index: 57, label: 'MIDI Channel 10' },
  { index: 58, label: 'MIDI Channel 12' },
  { index: 59, label: 'MIDI Channel 13' },
  { index: 60, label: 'MIDI Channel 14' },
  { index: 61, label: 'MIDI Channel 15' },
  { index: 62, label: 'MIDI Channel 16' },
];

export const EffectList: AttributeListItem[] = [
  { index: 0, symbol: '-', label: 'None' },
  { index: 1, symbol: '!', label: 'Off' },
  { index: 18, symbol: 'V', label: 'Volume/Velocity' },
  { index: 31, symbol: 'P', label: 'Panning' },
  { index: 34, symbol: 'M', label: 'Micro-tune/Pitchbend' },
  { index: 19, symbol: 'G', label: 'Glide' },
  { index: 15, symbol: 'T', label: 'Tempo' },
  { index: 17, symbol: 'I', label: 'Swing' },
  { index: 2, symbol: 'm', label: 'Micro-move' },
  { index: 20, symbol: 'q', label: 'Gate Length' },
  { index: 4, symbol: 'C', label: 'Chance' },
  { index: 3, symbol: 'R', label: 'Roll' },
  { index: 21, symbol: 'A', label: 'Arp' },
  { index: 5, symbol: 'n', label: 'Random Note' },
  { index: 6, symbol: 'i', label: 'Random Instrument' },
  { index: 16, symbol: 'x', label: 'Random FX Value' },
  { index: 7, symbol: 'v', label: 'Random Volume' },
  { index: 26, symbol: 'r', label: 'Reverse Playback' },
  { index: 22, symbol: 'p', label: 'Position' },
  { index: 25, symbol: 'S', label: 'Slice' },
  { index: 23, symbol: 'g', label: 'Volume LFO' },
  { index: 24, symbol: 'h', label: 'Panning LFO' },
  { index: 35, symbol: 'j', label: 'Filter LFO' },
  { index: 36, symbol: 'k', label: 'Position LFO' },
  { index: 33, symbol: 'l', label: 'Finetune LFO' },
  { index: 38, symbol: 'D', label: 'Overdrive' },
  { index: 27, symbol: 'L', label: 'Low-pass' },
  { index: 28, symbol: 'H', label: 'High-pass' },
  { index: 29, symbol: 'B', label: 'Band-pass' },
  { index: 30, symbol: 's', label: 'Delay Send' },
  { index: 32, symbol: 't', label: 'Reverb Send' },
  { index: 39, symbol: 'E', label: 'Bit Depth' },
  { index: 40, symbol: 'U', label: 'Tune' },
  { index: 41, symbol: 'F', label: 'Slide Up' },
  { index: 42, symbol: 'J', label: 'Slide Down' },
  { index: 8, symbol: 'a', label: 'MIDI CC A' },
  { index: 9, symbol: 'b', label: 'MIDI CC B' },
  { index: 10, symbol: 'c', label: 'MIDI CC C' },
  { index: 11, symbol: 'd', label: 'MIDI CC D' },
  { index: 12, symbol: 'e', label: 'MIDI CC E' },
  { index: 37, symbol: 'f', label: 'MIDI CC F' },
  { index: 14, symbol: '0', label: 'MIDI Chord' },
];

export const NoteToMidiMap: Record<string, number> = {
  C_Low: 12,
  CSharp: 13,
  D: 14,
  DSharp: 15,
  E: 16,
  F: 17,
  FSharp: 18,
  G: 19,
  GSharp: 20,
  A: 21,
  ASharp: 22,
  B: 23,
  C_High: 24,
};
